name: Auto Tag

on:
  push:
    branches:
      - main

jobs:
  auto-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create Tag
        run: |
          TAG="v0.1.3"
          git tag $TAG
          git push origin $TAG
