name: Auto Tag

on:
  push:
    branches:
      - main

jobs:
  auto-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Determine Tag
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "TAG=v$VERSION" >> $GITHUB_ENV

      - name: Create and Push Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag $TAG
          git push origin $TAG
