name: Build and Release

on:
  workflow_run:
    workflows:
      - Auto Tag
    types:
      - completed

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Ensure Tag Checkout
        run: |
          git fetch --tags
          git checkout ${{ github.ref }}

      - name: Install dependencies
        run: npm install

      - name: Build front
        run: npm run build

      - name: Electron Builder (Win + Publish)
        run: electron-builder -w --publish always
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
