name: Build and Release

on:
  workflow_run:
    workflows:
      - Auto Tag
    types:
      - completed

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-12]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Ensure Tag Checkout
        run: |
          git fetch --tags
          git checkout ${{ github.ref }}

      - name: Install dependencies
        run: npm install

      - name: Build front
        run: npm run build

      - name: Electron Builder (Windows Publish)
        if: runner.os == 'Windows'
        run: npx electron-builder --win --publish always
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Electron Builder (Linux Publish)
        if: runner.os == 'Linux'
        run: npx electron-builder --linux --publish always
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Electron Builder (macOS Publish)
        if: runner.os == 'macOS'
        run: npx electron-builder --mac --publish always
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
